// Spec adapter contract — documents what a spec adapter must export.
// This file is not imported directly. It exists as documentation and
// for runtime validation of adapter conformance.
//
// To add a new spec:
// 1. Create src/spec/{specname}.js exporting these symbols
// 2. Set spec.specName in config.json
// 3. Run `npm run build-data` to generate data for the new spec
// 4. Run `node src/spec/validate-spec-data.js` to verify constants
//
// Spec file structure — three sections:
//
//   // ================================================================
//   // SECTION 1: HUMAN DOMAIN KNOWLEDGE
//   // Edit when game mechanics, abilities, or set bonuses change.
//   // ================================================================
//
//   export const SPEC_CONFIG = { ... };      // identity, resources, spellIds, etc.
//   export const SET_BONUS_SPELL_IDS = ...;   // tier set spell IDs
//   export const STRUCT_TO_ABILITY_MAP = ...; // C++ struct → display name
//   export const CPP_SCANNER_SEEDS = ...;    // validation fixture
//
//   // ================================================================
//   // SECTION 2: MACHINE-VALIDATED DATA
//   // Sourced from SimC DBC, cross-checked by validate-spec-data.js.
//   // ================================================================
//
//   export const BASE_SPELL_IDS = ...;       // spec baseline abilities
//
//   // ================================================================
//   // SECTION 3: AUTO-DERIVED (do not edit)
//   // Generated by common.js from SPEC_CONFIG.
//   // ================================================================
//
//   // Derivable functions delegate to common.js:
//   // getClassSpellQuery(), getCppStructPatterns(), getSpecSpellFilter(),
//   // getTalentTreePattern(), getKeySpellIds()
//
// SPEC_CONFIG required fields:
//   - specId, className, cppClassName, role
//   - displayNames: { class, spec }
//   - resources: { primary: {name, cap}, secondary?: {name, cap} }
//   - spellIds, domainOverrides, heroTrees, resourceFlow
//   - buffWindows, synergies
//   - keyBuffs, offGcdAbilities, cooldownBuffs
//   - classificationHints, resourceNames
//
// Resource caps should be BASE values (without talents). Use validate-spec-data.js
// to catch values that accidentally include talent bonuses.

/**
 * @typedef {Object} SpecAdapter
 *
 * Required exports from a spec adapter module:
 *
 * @property {Set<number>} BASE_SPELL_IDS
 *   Spell IDs granted by the spec (not talents). Used by extraction to seed
 *   the spell catalog. These are find_specialization_spell() calls in simc C++.
 *
 * @property {Set<number>} SET_BONUS_SPELL_IDS
 *   Spell IDs from tier set bonuses. Separate from base abilities since they
 *   come from gear. Included in spell extraction.
 *
 * @property {Object} SPEC_CONFIG
 *   Static spec configuration. See SPEC_CONFIG required fields above.
 *
 * @property {function(): Object} getSpecConfig
 *   Returns SPEC_CONFIG.
 *
 * @property {function(): Object} loadAbilityData
 *   Merges spell data from spells-summary.json with domain overrides.
 *   Returns frozen object keyed by ability name.
 *
 * @property {function(): Object} getHeroTrees
 *   Returns hero tree configs from SPEC_CONFIG.
 *
 * @property {function(): Object} getResourceFlow
 *   Returns resource flow config from SPEC_CONFIG.
 *
 * @property {function(string): string|null} detectHeroTreeFromProfileName
 *   Given APL text, detects which hero tree is active from profile keywords.
 *
 * @property {function(Object): string|null} detectHeroTreeFromBuffs
 *   Given workflow results, detects hero tree from buff uptimes.
 *
 * @property {function(): Record<string, number>} getSpellIds
 *   Returns spell ID map from SPEC_CONFIG.
 *
 * @property {function(): Record<string, Object>} getDomainOverrides
 *   Returns domain override map from SPEC_CONFIG.
 *
 * @property {function(): void} clearCache
 *   Clears any cached ability data (for testing/reloads).
 *
 * @property {function(): Record<string,string>} getStructToAbilityMap
 *   Maps C++ struct names to display ability names. Used by cpp-interactions.js
 *   to resolve struct contexts to human-readable ability names.
 *
 * @property {function(): RegExp} getTalentTreePattern
 *   Returns regex matching C++ talent references for this class.
 *
 * @property {function(): Map<number, Object>} getSetBonusSpells
 *   Returns tier set bonus spell IDs with metadata (name, pieceCount, displayName).
 *
 * @property {function(): string} getClassSpellQuery
 *   Returns the simc spell_query class filter string.
 *
 * @property {function(Object): boolean} getSpecSpellFilter
 *   Returns a predicate to filter modifier spells to this spec.
 *
 * @property {function(): Object} getCppStructPatterns
 *   Returns C++ struct name patterns for this class.
 *
 * @property {function(): Array} getKeySpellIds
 *   Returns [[id, displayName], ...] pairs for key spec abilities.
 *
 * @property {function(): Object} getSiblingSpecs
 *   Returns { siblingSpec, siblingHeroTrees } for contamination detection.
 */

const REQUIRED_EXPORTS = [
  "BASE_SPELL_IDS",
  "SET_BONUS_SPELL_IDS",
  "SPEC_CONFIG",
  "getSpecConfig",
  "loadAbilityData",
  "getHeroTrees",
  "getResourceFlow",
  "detectHeroTreeFromProfileName",
  "detectHeroTreeFromBuffs",
  "getSpellIds",
  "getDomainOverrides",
  "clearCache",
  "getStructToAbilityMap",
  "getTalentTreePattern",
  "getSetBonusSpells",
  "getClassSpellQuery",
  "getSpecSpellFilter",
  "getCppStructPatterns",
  "getKeySpellIds",
  "getSiblingSpecs",
];

/**
 * Validates that a loaded module conforms to the spec adapter contract.
 * @param {Object} mod — The imported module
 * @param {string} specName — For error messages
 * @returns {{ valid: boolean, missing: string[] }}
 */
export function validateAdapter(mod, specName) {
  const missing = REQUIRED_EXPORTS.filter((name) => !(name in mod));
  return {
    valid: missing.length === 0,
    missing,
  };
}

export { REQUIRED_EXPORTS };
